###Redis配置
spring:
  datasource:
    name: orcl
    url: jdbc:oracle://192.168.1.4:1521/orcl
    username: tydic01
    password: tydic01
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
