debug: false
#读取log配置文件
logging:
  config: classpath:logback-boot.xml
server:
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  messages:
    encoding: utf-8
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.xch.study.biz

#pagehelper分页插件
pagehelper:
    helperDialect: oracle
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

log:
  path: E:/log/sys.log



