#redis
# REDIS (RedisProperties)
# Redis数据库索引（默认为0）
spring:
  redis:
      #数据库索引
      database: 0
      host: 192.168.1.5
      port: 6379
      password:
      jedis:
        pool:
          #连接池最大连接（使用负值标识没有限制）
          max-active: 8
          #连接池最大阻塞时间（使用负值标识没有限制）
          max-wait: -1
          #连接池中最大空闲连接数
          max-idle: 5
          #连接池中最小空闲连接数
          min-idle: 0
      #连接超时时间
      timeout: 10000