server:
  port: 18080
  servlet:
    context-path: /study
spring:
  profiles:
    active: dev,redis,db,es
#mybatis:
#  configuration-properties: classpath:mybatis-config.xml
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.xch.study.biz.*.entity
